### ISSUE TITLE
GitHub Auth Strategy

### ISSUE THREAD

**Issue by wavded** [Amwam/Jenkins-Alfred-Workflow#1]
Thanks for working on this!  My Jenkins uses a GitHub Authorization strategy and doesn't seem to work with this workflow?  Is that a possibility?

**Comment by Amwam** [comment]
Sorry this has taken so long, I have a branch which i _think_ will work. However I'm getting SSL errors when I attempt to test it myself. Would you be interested in testing this out?

**Comment by Amwam** [comment]
Closing this now, the workflow requires logging in via the API token, rather than with a password. So should work with any authentication strategy.
