### ISSUE TITLE
Hold cmd key to go to build page of a job

### ISSUE THREAD

**Issue by Strajk** [Amwam/Jenkins-Alfred-Workflow#5]
Thanks for great workflow, using many times every day... :)

It would be awesome if I could hold cmd key (or other meta key) while selecting a job to go to its build page... `job/Beta/` -> `job/Beta/build` I know it's easy to click on Build in left menu, but when I'm doing that 50 times a day, my mind will start thinking how to improve that :)

I've seen this pattern with slighly modifing actions with modifier keys in a lot of other workflows.

**Comment by Amwam** [comment]
I like this idea! Would you think its better to trigger a build, then open the console for that build, or just take you to the normal page, so you can trigger the build yourself?

**Comment by Strajk** [comment]
I would like to trigger build directly, but we have lots of setable parameters on a lot of jobs...
Maybe cmd to go to build page and cmd + alt to build with defaults? :)

I'd do it myself but I've never written a line in python (yet) :)

**Comment by Amwam** [comment]
I agree, both options would be best. Next time I get a chance, I'll take i'll see if I can add this in. Should be pretty simple :+1:
